java -cp src PrimeSieveI32CQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CReference -warmup >> results.txt
java -cp src PrimeSieveI32CReference -warmup >> results.txt
java -cp src PrimeSieveI32CReference -warmup >> results.txt
java -cp src PrimeSieveI32CReference -warmup >> results.txt
java -cp src PrimeSieveI32CReference -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollQAndSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollReference -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollReference -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollReference -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollReference -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollReference -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextQ -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextSize -warmup >> results.txt
java -cp src PrimeSieveI32CUnrollSearchNextSize -warmup >> results.txt
cat results.txt